version: "3.9"

services:
  postgres-allure-server:
    image: postgres:12.0-alpine
    healthcheck:
      test: "pg_isready -q -h db"
      interval: 3s
      timeout: 5s
      retries: 5
    env_file:
      - .env
    ports:
      - "5434:5432"

  allure-server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - '.:/app'
    ports:
      - "8000:8000"
    depends_on:
      - postgres-allure-server
